<p>&nbsp;</p>

# **IST 736 HOMEWORK 7**

<p>&nbsp;</p>

In [1]:
# Import standard packages
import pandas
import numpy

# Import packages from scikit-learn
from sklearn.pipeline import Pipeline
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import KFold
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

<p>&nbsp;</p>

# **TASK 1 - UNIGRAM VECTORS**

<p>&nbsp;</p>

In [2]:
# Import data
data_train = pandas.read_csv("train.tsv", delimiter = "\t")
data_test = pandas.read_csv("test.tsv", delimiter = "\t")
X = data_train.Phrase.copy()
y = data_train.Sentiment.copy()

In [3]:
# Split data into test/train
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4, random_state = 42)

In [4]:
# Take a look at the class balances
print("Train Class Balance", "\n", y_train.value_counts(), "\n")
print("Test Class Balance", "\n", y_test.value_counts())

Train Class Balance 
 2    47985
3    19608
1    16348
4     5448
0     4247
Name: Sentiment, dtype: int64 

Test Class Balance 
 2    31597
3    13319
1    10925
4     3758
0     2825
Name: Sentiment, dtype: int64


In [5]:
# Initiate vectorizer
unigram_count_vectorizer = CountVectorizer(
	encoding = "latin-1",
	binary = False,
	min_df = 5,
	stop_words = "english"
)

# Fit the vectorizer on the train data and vectorize the train data
X_train_vec = unigram_count_vectorizer.fit_transform(X_train)

# Vectorize the test data
X_test_vec = unigram_count_vectorizer.transform(X_test)

In [6]:
# Train a MNB classifier
nb_clf = MultinomialNB()
nb_clf.fit(X_train_vec, y_train)
print(nb_clf.score(X_test_vec,y_test))

0.6040625400486992


In [7]:
# Train a SVM classifier
svm_clf = LinearSVC(C = 1, max_iter = 10000)
svm_clf.fit(X_train_vec, y_train)
print(svm_clf.score(X_test_vec, y_test))

0.6218922209406639


In [8]:
# Print the confusion matrix for mnb and svm
print("Confusion Matrix for MNB Model", "\n")
print(confusion_matrix(y_test, nb_clf.predict(X_test_vec), labels = [0,1,2,3,4]), "\n")
print("Confusion Matrix for SVM Model", "\n")
print(confusion_matrix(y_test, svm_clf.predict(X_test_vec), labels = [0,1,2,3,4]), "\n")
print("Difference of SVM and MNB", "\n")
print(confusion_matrix(y_test, nb_clf.predict(X_test_vec), labels = [0,1,2,3,4]) -
      confusion_matrix(y_test, svm_clf.predict(X_test_vec), labels = [0,1,2,3,4]), "\n")

Confusion Matrix for MNB Model 

[[  703  1291   723    94    14]
 [  618  4123  5507   628    49]
 [  228  2417 25570  3168   214]
 [   32   486  5691  6316   794]
 [    3    56   703  2000   996]] 

Confusion Matrix for SVM Model 

[[  876  1225   633    72    19]
 [  710  4025  5587   540    63]
 [  189  2106 26901  2241   160]
 [   42   420  6131  5674  1052]
 [    7    45   585  1776  1345]] 

Difference of SVM and MNB 

[[ -173    66    90    22    -5]
 [  -92    98   -80    88   -14]
 [   39   311 -1331   927    54]
 [  -10    66  -440   642  -258]
 [   -4    11   118   224  -349]] 



In [9]:
# Print the precision, recall, and classification report for mnb
print("Precision for MNB Model")
print(precision_score(y_test, nb_clf.predict(X_test_vec), average = None), "\n")
print("Recall for MNB Model")
print(recall_score(y_test, nb_clf.predict(X_test_vec), average = None), "\n")
print("Classification Report for MNB Model")
print(classification_report(y_test, nb_clf.predict(X_test_vec), target_names = ["0","1","2","3","4"]), "\n")

Precision for MNB Model
[0.44381313 0.4924161  0.66947688 0.51745043 0.48185776] 

Recall for MNB Model
[0.24884956 0.3773913  0.80925404 0.47420978 0.26503459] 

Classification Report for MNB Model
              precision    recall  f1-score   support

           0       0.44      0.25      0.32      2825
           1       0.49      0.38      0.43     10925
           2       0.67      0.81      0.73     31597
           3       0.52      0.47      0.49     13319
           4       0.48      0.27      0.34      3758

    accuracy                           0.60     62424
   macro avg       0.52      0.43      0.46     62424
weighted avg       0.58      0.60      0.59     62424
 



In [10]:
# Print the precision, recall, and classification report for svm
print("Precision for SVM Model")
print(precision_score(y_test, svm_clf.predict(X_test_vec), average = None), "\n")
print("Recall for SVM Model")
print(recall_score(y_test, svm_clf.predict(X_test_vec), average = None), "\n")
print("Classification Report for SVM Model")
print(classification_report(y_test, svm_clf.predict(X_test_vec), target_names = ["0","1","2","3","4"]), "\n")

Precision for SVM Model
[0.48026316 0.51464007 0.67527675 0.55071338 0.50966275] 

Recall for SVM Model
[0.3100885  0.36842105 0.8513783  0.42600796 0.35790314] 

Classification Report for SVM Model
              precision    recall  f1-score   support

           0       0.48      0.31      0.38      2825
           1       0.51      0.37      0.43     10925
           2       0.68      0.85      0.75     31597
           3       0.55      0.43      0.48     13319
           4       0.51      0.36      0.42      3758

    accuracy                           0.62     62424
   macro avg       0.55      0.46      0.49     62424
weighted avg       0.60      0.62      0.60     62424
 



In [11]:
# Save the feature ranks
feature_ranks_very_neg_mnb = sorted(zip(nb_clf.feature_log_prob_[0], unigram_count_vectorizer.get_feature_names()))
feature_ranks_very_pos_mnb = sorted(zip(nb_clf.feature_log_prob_[4], unigram_count_vectorizer.get_feature_names()))
feature_ranks_very_neg_svm = sorted(zip(svm_clf.coef_[0], unigram_count_vectorizer.get_feature_names()))
feature_ranks_very_pos_svm = sorted(zip(svm_clf.coef_[4], unigram_count_vectorizer.get_feature_names()))

In [12]:
# Top 10 very negative for mnb and svm
print("Top 10 Indicative Words for Very Negative Category MNB Model", "\n")
print(feature_ranks_very_neg_mnb[-10: ], "\n")
print("Top 10 Indicative Words for Very Negative Category SVM Model", "\n")
print(feature_ranks_very_neg_svm[-10: ])

Top 10 Indicative Words for Very Negative Category MNB Model 

[(-5.998191867857409, 'does'), (-5.998191867857409, 'time'), (-5.987142031670825, 'comedy'), (-5.965402045034418, 'minutes'), (-5.8632725499580385, 'characters'), (-5.615199615601304, 'just'), (-5.204696713463182, 'like'), (-4.873984032000336, 'bad'), (-4.8246782710161815, 'film'), (-4.341022552602119, 'movie')] 

Top 10 Indicative Words for Very Negative Category SVM Model 

[(1.5336166732805725, 'awfulness'), (1.5405298274665544, 'dehumanizing'), (1.5433730699417667, 'disappointment'), (1.5758202783829676, 'turd'), (1.6000339723511974, 'worthless'), (1.6015543663565792, 'repulsive'), (1.6573642229516043, 'unappealing'), (1.7640482390775962, 'unbearable'), (1.8708641459657862, 'dud'), (2.0389985608287358, 'unwatchable')]


In [13]:
# Top 10 very positive for mnb and svm
print("Top 10 Indicative Words for Very Positive Category MNB Model", "\n")
print(feature_ranks_very_pos_mnb[-10: ], "\n")
print("Top 10 Indicative Words for Very Positive Category SVM Model", "\n")
print(feature_ranks_very_pos_svm[-10: ])

Top 10 Indicative Words for Very Positive Category MNB Model 

[(-5.822900380967689, 'performance'), (-5.782734339242355, 'great'), (-5.706940499872821, 'performances'), (-5.706940499872821, 'story'), (-5.61628613160469, 'comedy'), (-5.390479462870997, 'good'), (-5.270335151028934, 'funny'), (-5.150457873769435, 'best'), (-4.809810265737742, 'movie'), (-4.286562121973194, 'film')] 

Top 10 Indicative Words for Very Positive Category SVM Model 

[(1.5381360711706258, 'glorious'), (1.572364679976549, 'proud'), (1.6261953718029958, 'praiseworthy'), (1.6394560491723595, 'standout'), (1.7019432057944854, 'zings'), (1.7518054155415512, 'luminous'), (1.7856524779850782, 'astoundingly'), (1.8370938031766693, 'perfection'), (1.8922061253831526, 'celebrated'), (1.9519104812622925, 'refreshes')]


<p>&nbsp;</p>

# **TASK 2 - UNIGRAM AND BIGRAM VECTORS**

<p>&nbsp;</p>

In [14]:
# Initiate vectorizer
gram12_count_vectorizer = CountVectorizer(
	encoding = "latin-1",
    ngram_range = (1,2),
	min_df = 5,
	stop_words = "english"
)

# Fit the vectorizer on the train data and vectorize the train data
X_train_vec = gram12_count_vectorizer.fit_transform(X_train)

# Vectorize the test data
X_test_vec = gram12_count_vectorizer.transform(X_test)

In [15]:
# Train a MNB classifier
nb_clf = MultinomialNB()
nb_clf.fit(X_train_vec, y_train)
print(nb_clf.score(X_test_vec,y_test))

0.5952197872613098


In [16]:
# Train a SVM classifier
svm_clf = LinearSVC(C = 1, max_iter = 100000)
svm_clf.fit(X_train_vec, y_train)
print(svm_clf.score(X_test_vec, y_test))

0.6284441881327695


In [17]:
# Print the confusion matrix for mnb and svm
print("Confusion Matrix for MNB Model", "\n")
print(confusion_matrix(y_test, nb_clf.predict(X_test_vec), labels = [0,1,2,3,4]), "\n")
print("Confusion Matrix for SVM Model", "\n")
print(confusion_matrix(y_test, svm_clf.predict(X_test_vec), labels = [0,1,2,3,4]), "\n")
print("Difference of SVM and MNB", "\n")
print(confusion_matrix(y_test, nb_clf.predict(X_test_vec), labels = [0,1,2,3,4]) -
      confusion_matrix(y_test, svm_clf.predict(X_test_vec), labels = [0,1,2,3,4]), "\n")

Confusion Matrix for MNB Model 

[[  809  1268   644    89    15]
 [  814  4404  5038   610    59]
 [  387  3034 24254  3574   348]
 [   55   520  5180  6489  1075]
 [    7    60   592  1899  1200]] 

Confusion Matrix for SVM Model 

[[  979  1305   464    61    16]
 [  857  4535  5012   473    48]
 [  239  2502 25948  2742   166]
 [   46   347  5397  6281  1248]
 [   10    29   444  1788  1487]] 

Difference of SVM and MNB 

[[ -170   -37   180    28    -1]
 [  -43  -131    26   137    11]
 [  148   532 -1694   832   182]
 [    9   173  -217   208  -173]
 [   -3    31   148   111  -287]] 



In [18]:
# Print the precision, recall, and classification report for mnb
print("Precision for MNB Model")
print(precision_score(y_test, nb_clf.predict(X_test_vec), average = None), "\n")
print("Recall for MNB Model")
print(recall_score(y_test, nb_clf.predict(X_test_vec), average = None), "\n")
print("Classification Report for MNB Model")
print(classification_report(y_test, nb_clf.predict(X_test_vec), target_names = ["0","1","2","3","4"]), "\n")

Precision for MNB Model
[0.39044402 0.47426233 0.67923154 0.51251876 0.44493882] 

Recall for MNB Model
[0.28637168 0.40311213 0.76760452 0.48719874 0.31931879] 

Classification Report for MNB Model
              precision    recall  f1-score   support

           0       0.39      0.29      0.33      2825
           1       0.47      0.40      0.44     10925
           2       0.68      0.77      0.72     31597
           3       0.51      0.49      0.50     13319
           4       0.44      0.32      0.37      3758

    accuracy                           0.60     62424
   macro avg       0.50      0.45      0.47     62424
weighted avg       0.58      0.60      0.58     62424
 



In [19]:
# Print the precision, recall, and classification report for svm
print("Precision for SVM Model")
print(precision_score(y_test, svm_clf.predict(X_test_vec), average = None), "\n")
print("Recall for SVM Model")
print(recall_score(y_test, svm_clf.predict(X_test_vec), average = None), "\n")
print("Classification Report for SVM Model")
print(classification_report(y_test, svm_clf.predict(X_test_vec), target_names = ["0","1","2","3","4"]), "\n")

Precision for SVM Model
[0.45940873 0.52018812 0.69631021 0.55363596 0.50151771] 

Recall for SVM Model
[0.34654867 0.41510297 0.8212172  0.47158195 0.3956892 ] 

Classification Report for SVM Model
              precision    recall  f1-score   support

           0       0.46      0.35      0.40      2825
           1       0.52      0.42      0.46     10925
           2       0.70      0.82      0.75     31597
           3       0.55      0.47      0.51     13319
           4       0.50      0.40      0.44      3758

    accuracy                           0.63     62424
   macro avg       0.55      0.49      0.51     62424
weighted avg       0.61      0.63      0.62     62424
 



In [20]:
# Save the feature ranks
feature_ranks_very_neg_mnb = sorted(zip(nb_clf.feature_log_prob_[0], unigram_count_vectorizer.get_feature_names()))
feature_ranks_very_pos_mnb = sorted(zip(nb_clf.feature_log_prob_[4], unigram_count_vectorizer.get_feature_names()))
feature_ranks_very_neg_svm = sorted(zip(svm_clf.coef_[0], unigram_count_vectorizer.get_feature_names()))
feature_ranks_very_pos_svm = sorted(zip(svm_clf.coef_[4], unigram_count_vectorizer.get_feature_names()))

In [21]:
# Top 10 very negative for mnb and svm
print("Top 10 Indicative Words for Very Negative Category MNB Model", "\n")
print(feature_ranks_very_neg_mnb[-10: ], "\n")
print("Top 10 Indicative Words for Very Negative Category SVM Model", "\n")
print(feature_ranks_very_neg_svm[-10: ])

Top 10 Indicative Words for Very Negative Category MNB Model 

[(-7.272981555830627, 'cloying'), (-7.107467117353054, 'anachronistic'), (-6.980311941867808, 'phrase'), (-6.854271220972443, 'retaliatory'), (-6.802977926584893, 'animals'), (-6.685194890928509, 'purists'), (-6.674145054741924, 'innocuous'), (-6.550275573029138, 'generosity'), (-5.560987055071435, 'confession'), (-5.511681294087281, 'undermining')] 

Top 10 Indicative Words for Very Negative Category SVM Model 

[(1.532896493786733, 'smash'), (1.5428904827358356, 'atypically'), (1.5638131694848745, 'proper'), (1.6406563014286202, 'predicament'), (1.6530806397243731, 'results'), (1.6983640253240764, 'meddles'), (1.706159275130978, 'stereotyped'), (1.7293156995789352, 'relevance'), (1.7771190757844315, 'complications'), (1.8892389955847735, 'precocious')]


In [22]:
# Top 10 very positive for mnb and svm
print("Top 10 Indicative Words for Very Positive Category MNB Model", "\n")
print(feature_ranks_very_pos_mnb[-10: ], "\n")
print("Top 10 Indicative Words for Very Positive Category SVM Model", "\n")
print(feature_ranks_very_pos_svm[-10: ])

Top 10 Indicative Words for Very Positive Category MNB Model 

[(-6.957636910776074, 'floria'), (-6.957636910776074, 'tied'), (-6.9313196024587, 'reduce'), (-6.820777728058877, 'pork'), (-6.8092169056578005, 'veil'), (-6.753336447263344, 'generosity'), (-6.753336447263344, 'slasher'), (-6.264489730216129, 'innocuous'), (-5.798661472380873, 'defiance'), (-4.9347657205846325, 'undermining')] 

Top 10 Indicative Words for Very Positive Category SVM Model 

[(1.436821695395699, 'nuances'), (1.4574568221895732, 'landau'), (1.4623816688376123, 'operandi'), (1.498729931615342, 'complicated'), (1.5015474508026285, 'nephew'), (1.5265681411640997, 'startled'), (1.5775369722317834, 'suffocation'), (1.6072914745057028, 'blacks'), (1.759757468229615, 'start'), (1.8745669202066426, 'drowsy')]


<p>&nbsp;</p>

# **TASK 3 - BEST CLASSIFIER**

<p>&nbsp;</p>

In [23]:
# Set up the vectorization pipeline
tfidf_pip = Pipeline([
    ("tfidf_vectorizer", TfidfVectorizer())
])

In [24]:
# Set up the naive bayes pipeline
mnb_pipeline = Pipeline([
    ("tfidf_pip", tfidf_pip),
    ("mnb", MultinomialNB())
])

In [25]:
# Set up the grid search params
grid_params = {
  "mnb__alpha": numpy.linspace(0.5, 1.5, 3),
  'mnb__fit_prior': [True, False],
  "tfidf_pip__tfidf_vectorizer__use_idf": [True, False],
  "tfidf_pip__tfidf_vectorizer__norm": [None, "l1", "l2"], 
}

In [37]:
# Train model
nb_clf = GridSearchCV(mnb_pipeline, grid_params)
nb_clf.fit(X_train, y_train)
predictions = nb_clf.predict(X_test)
print("Train Score = ", nb_clf.best_score_)
print("Test Score = ", accuracy_score(y_test, predictions))
print("Best Params = ", nb_clf.best_params_)

Train Score =  0.6019479717418196
Test Score =  0.6081475073689606
Best Params =  {'mnb__alpha': 1.5, 'mnb__fit_prior': True, 'tfidf_pip__tfidf_vectorizer__norm': None, 'tfidf_pip__tfidf_vectorizer__use_idf': False}


In [41]:
# Fit vectorizer and MNB with the params

vectorizer = TfidfVectorizer(
    norm = None,
    use_idf = False
)

nb_clf = MultinomialNB(alpha = 1.5, fit_prior = True)

In [55]:
# Initiate the split object
split = KFold(n_splits = 10, shuffle = True, random_state = 42)

# Initiate a counter
run_counter = 0

# Iterate through each fold and conduct the process
for train_index, test_index in split.split(data_train, data_train["Sentiment"]):

    # Seperate out the train and test sets
    train_data = data_train.iloc[train_index, :]
    test_data = data_train.iloc[test_index, :]
    
    # Separate out the predictors
    X_train = train_data["Phrase"]
    X_train_vec = vectorizer.fit_transform(X_train)
    X_test = test_data["Phrase"]
    X_test_vec = vectorizer.transform(X_test)
    
    # Seperate out the class labels
    y_train = train_data["Sentiment"].copy()
    y_test = test_data["Sentiment"].copy()

    # Train model and and make predictions
    nb_clf.fit(X_train_vec, y_train)
    predictions = nb_clf.predict(X_test_vec)

    # Store the information from the run
    test_score = accuracy_score(y_test, predictions)

    # Update the counter after each iteration
    run_counter += 1

    # Print out the results
    print("Run ", run_counter, " Completed")
    print("Test Score ", test_score)

Run  1  Completed
Test Score  0.6148276303985647
Run  2  Completed
Test Score  0.6138023836985774
Run  3  Completed
Test Score  0.6190567730360118
Run  4  Completed
Test Score  0.6099577085736255
Run  5  Completed
Test Score  0.6120082019736
Run  6  Completed
Test Score  0.6130334486735871
Run  7  Completed
Test Score  0.6090606177111367
Run  8  Completed
Test Score  0.6146994745610662
Run  9  Completed
Test Score  0.6084198385236448
Run  10  Completed
Test Score  0.6186723055235166


In [26]:
# Set up the vectorization pipeline
tfidf_pip = Pipeline([
    ("tfidf_vectorizer", TfidfVectorizer())
])

In [31]:
# Set up the naive bayes pipeline
svm_pipeline = Pipeline([
    ("tfidf_pip", tfidf_pip),
    ("svm", LinearSVC(max_iter = 100000))
])

In [34]:
# Set up the grid search params
grid_params = {
  "svm__C": numpy.linspace(1, 10, 3),
  "tfidf_pip__tfidf_vectorizer__use_idf": [True, False],
}

In [35]:
# Train model
svm_clf = GridSearchCV(svm_pipeline, grid_params)
svm_clf.fit(X_train, y_train)
predictions = svm_clf.predict(X_test)
print("Train Score = ", svm_clf.best_score_)
print("Test Score = ", accuracy_score(y_test, predictions))
print("Best Params = ", svm_clf.best_params_)

Train Score =  0.629672306900651
Test Score =  0.6347718826092529
Best Params =  {'svm__C': 1.0, 'tfidf_pip__tfidf_vectorizer__use_idf': False}


In [36]:
# Fit vectorizer and SVM with the params

vectorizer = TfidfVectorizer(use_idf = False)

svm_clf = LinearSVC()

In [37]:
# Initiate the split object
split = KFold(n_splits = 10, shuffle = True, random_state = 42)

# Initiate a counter
run_counter = 0

# Iterate through each fold and conduct the process
for train_index, test_index in split.split(data_train, data_train["Sentiment"]):

    # Seperate out the train and test sets
    train_data = data_train.iloc[train_index, :]
    test_data = data_train.iloc[test_index, :]
    
    # Separate out the predictors
    X_train = train_data["Phrase"]
    X_train_vec = vectorizer.fit_transform(X_train)
    X_test = test_data["Phrase"]
    X_test_vec = vectorizer.transform(X_test)
    
    # Seperate out the class labels
    y_train = train_data["Sentiment"].copy()
    y_test = test_data["Sentiment"].copy()

    # Train model and and make predictions
    svm_clf.fit(X_train_vec, y_train)
    predictions = svm_clf.predict(X_test_vec)

    # Store the information from the run
    test_score = accuracy_score(y_test, predictions)

    # Update the counter after each iteration
    run_counter += 1

    # Print out the results
    print("Run ", run_counter, " Completed")
    print("Test Score ", test_score)

Run  1  Completed
Test Score  0.6441112392669486
Run  2  Completed
Test Score  0.6433423042419583
Run  3  Completed
Test Score  0.6496219402793797
Run  4  Completed
Test Score  0.6423811354607203
Run  5  Completed
Test Score  0.6475714468794054
Run  6  Completed
Test Score  0.6477636806356529
Run  7  Completed
Test Score  0.6399461745482506
Run  8  Completed
Test Score  0.6455850313981802
Run  9  Completed
Test Score  0.6425092912982187
Run  10  Completed
Test Score  0.6496860181981289


In [41]:
# Kaggle submission
vectorizer = TfidfVectorizer(use_idf = False)
X_vec = vectorizer.fit_transform(X)
svm_clf = LinearSVC()
svm_clf.fit(X_vec, y)
X_kaggle = data_test.Phrase.copy()
ids = data_test.PhraseId.copy()
X_kaggle_vec = vectorizer.transform(X_kaggle)
predictions = svm_clf.predict(X_kaggle_vec)
submission = pandas.DataFrame(list(zip(
    ids, predictions)), columns = ["PhraseId", "Sentiment"])
submission.to_csv("submission.csv", index = False)